const express=require('express');
const router=express.Router();
const passport=require('passport');
const usersController=require('../controllers/users_controller');
router.get('/signUp',usersController.signUp);
router.get('/signIn',usersController.signIn);
router.get('/profile',passport.checkAuthentication,usersController.profile);
router.get('/sign-out',usersController.destroySession);
router.post('/create',usersController.create);
router.post('/create-session',passport.authenticate('local',{failureRedirect:'/users/signIn'}),usersController.createSession);
router.get('/profile/:id',passport.checkAuthentication,usersController.profile);
router.post('/update/:id',passport.checkAuthentication,usersController.update);
router.get('/auth/google',passport.authenticate('google',{scope:['profile','email']}));
router.get('/auth/google/callback',passport.authenticate('google',{failureRedirect:'/users/signIn'}),usersController.createSession);
module.exports=router;